save_dir: /vol/data/trainings/omega/1to50hz_ss/brainomni_tok/subject
resume_from: null

model_name: BrainOmniCausalTokenizer
loss_name: BrainOmniCausalTokenizerLoss
model_config: configs/brainomni_tok/omega_subject/tokenizer8x_60s.yaml

datasplitter:
  dataset_class: ChunkDatasetReconstruction
  dataset_root: /vol/data/datasets/omega/full/1to50hz_ss_cont
  example_seconds: 57.6
  overlap_seconds: 0.0
  val_ratio: 0.1
  test_ratio: 0.1
  split_strategy: subject
  refresh_cache: false  # need to refresh if any datasplitter args change
  cache_dir: /vol/data/datasets/omega/full/cache/1to50hz_ss_cont_57.6s_subject

dataloader:
  batch_size: 8
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

eval_runner:
  enabled: true
  max_batches: 100
  num_examples: 5

lightning:
  lr: 2.0e-4
  weight_decay: 0.0
  compile: false
  lr_scheduler:
    class_name: CosineAnnealingLR
    eta_min: 2.0e-5
    T_max: 100

trainer:
  tune_batch_size: true
  max_epochs: 100
  accelerator: cuda
  check_val_every_n_epoch: 1
  checkpoint_cadence_epochs: 5
  log_every_n_steps: 200
  precision: bf16-mixed
  gradient_clip_val: 1.0  # trying higher value
  early_stopping:
    monitor: val/loss
    patience: 5
