trf_class: SmoLLM3
tok_class: AmplitudeTokenizerMix
hidden_size: 544
vocab_size: 256
input_shape: [1000, 68, 1]  # T, H, W

mix_method: mix

trf_args:
  intermediate_size: 2176
  num_hidden_layers: 8
  num_attention_heads: 8
  num_key_value_heads: 2
  attention_dropout: 0.0

  max_position_embeddings: 1024
  pad_token_id: null
  no_rope_layer_interval: 4
  rope_theta: 1000000.0

  _attn_implementation: sdpa

  no_rope_layers: [
    1,
    1,
    1,
    0,
    1,
    1,
    1,
    0,
  ]