save_dir: /vol/data/trainings/omega/1to50hz_ss_cont/brainomni_tok/60s
resume_from: null

model_name: BrainOmniCausalTokenizer
loss_name: BrainOmniCausalTokenizerLoss
model_config: configs/brainomni_tok/omega_session/tokenizer60s.yaml

datasplitter:
  dataset_class: ChunkDatasetReconstruction
  dataset_root: /vol/data/datasets/omega/full/1to50hz_ss_cont
  example_seconds: 61.44
  overlap_seconds: 30.0
  val_ratio: 0.1
  test_ratio: 0.1
  refresh_cache: false  # need to refresh if any datasplitter args change
  cache_dir: /vol/data/datasets/omega/full/cache/1to50hz_ss_cont_61.44s

dataloader:
  batch_size: 7
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true
  drop_last: true

eval_runner:
  enabled: true
  max_batches: 100
  num_examples: 10

lightning:
  lr: 1.0e-4
  weight_decay: 0.0
  lr_scheduler:
    T_max: 100
    class_name: CosineAnnealingLR
    eta_min: 1.0e-05

trainer:
  tune_batch_size: false
  accelerator: cuda
  precision: bf16-mixed
  gradient_clip_val: 1.0

  max_epochs: 100
  check_val_every_n_epoch: 1
  checkpoint_cadence_epochs: 5
  log_every_n_steps: 1000
  num_sanity_val_steps: 0

  early_stopping:
    monitor: val/loss
    patience: 5
