window_length: 1024
ratios: [2, 2]
kernel_size: 5
last_kernel_size: 5
n_filters: 1024
n_dim: 4096
n_neuro: 4

lstm_layers: 0  # 2
n_residual_layers: 2  # 1

codebook_size: 16384
codebook_dim: 1024
num_quantizers: 4

compile: true
num_sensors: 68
n_head: 2
