# Scaled-down BrainTokMix tokenizer config for local CPU runs.

window_length: 1024
ratios: [2, 2]
kernel_size: 5
last_kernel_size: 5
n_filters: 128
n_dim: 512
n_neuro: 4

lstm_layers: 0
n_residual_layers: 1

codebook_size: 1024
codebook_dim: 128
num_quantizers: 2

compile: false
num_sensors: 68
n_head: 2
